# Generated by Django 6.0.4 on 2026-04-30 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=42, verbose_name='Название страны')),
                ('country_abbr', models.CharField(max_length=3, verbose_name='Название страны, сокращенно')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Справочник стран',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=42, verbose_name='Имя пилота')),
                ('driver_abbr', models.CharField(max_length=3, verbose_name='Имя пилота, сокращенно')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения пилота')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='f1_project.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Пилот',
                'verbose_name_plural': 'Таблица пилотов',
            },
        ),
        migrations.CreateModel(
            name='GrandPrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_prix', models.CharField(max_length=42, verbose_name='Название Гран При')),
                ('gp_abbr', models.CharField(max_length=3, verbose_name='Название Гран При, сокращенное')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='f1_project.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Гран При',
                'verbose_name_plural': 'Таблица Гран При',
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Дата проведения Гран При')),
                ('grd', models.IntegerField(verbose_name='Позиция на стартовой решетке')),
                ('pos', models.CharField(max_length=3, verbose_name='Позиция по итогам гонки')),
                ('pts', models.IntegerField(verbose_name='Количество заработанных очков')),
                ('pp', models.BooleanField(default=False, verbose_name='Поул позиция')),
                ('fl', models.BooleanField(default=False, verbose_name='Быстрый круг')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1_project.driver', verbose_name='Пилот')),
                ('grand_prix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1_project.grandprix', verbose_name='Гран При')),
            ],
            options={
                'verbose_name': 'Результат гонки',
                'verbose_name_plural': 'Турнирная таблица',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=42, verbose_name='Название команды')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='f1_project.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Таблица команд',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала выступления за команду')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания выступления за команду')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1_project.driver', verbose_name='Пилот')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1_project.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Трансфер',
                'verbose_name_plural': 'Таблица перемещений пилотов',
            },
        ),
    ]
