# Generated by Django 6.0.4 on 2026-05-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='flags/', verbose_name='Флаг'),
        ),
    ]
