# Generated by Django 6.0.4 on 2026-05-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_project', '0002_country_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.FileField(blank=True, null=True, upload_to='flags/', verbose_name='Флаг'),
        ),
    ]
