# Generated by Django 6.0.4 on 2026-05-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_project', '0003_alter_country_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_abbr',
            field=models.CharField(default='', max_length=3, verbose_name='Название команды, сокращенно'),
            preserve_default=False,
        ),
    ]
